# Makefile

CC = gcc
CFLAGS = -Wall -Werror

# .PHONY: all
# all: getline atoi itoa strindex

getline: getline.c
	$(CC) $(CFLAGS) getline.c -o getline

 atoi: atoi.c
	$(CC) $(CFLAGS) atoi.c -o atoi

itoa: itoa.c
	$(CC) $(CFLAGS) itoa.c -o itoa

# strindex: strindex.c
# 	$(CC) $(CFLAGS) strindex.c -o strindex
